#!/bin/sh
# Download latest infections.txt file for the Infection Scanner plugin 
# NOTE: This plugin was solely designed to show how easy it is to create a plugin
# within cPanel.  While it can be used for your customers, it will likely not receive
# many updates and therefore should not be solely relied upon as a malware scanner.
# 
# There are many other much better scanners available that should be used.
# 
/usr/bin/curl -s https://raw.githubusercontent.com/cPanelPeter/infection_scanner/master/infections.txt > /usr/local/cpanel/base/frontend/paper_lantern/infection_scanner/infections.txt

